name: test

on: ['push', 'pull_request']

env:
  DNSIMPLE_ACCOUNT_NUMBER: ${{ secrets.DNSIMPLE_ACCOUNT_NUMBER }}

jobs:
  octodns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '2.7'
      - name: Install OctoDNS
        run: pip install octodns
      - name: Do a dry run
        run: ./bin/dry-run
